class Table {
  String name
}

class Row {
}

class Type {
  String name
  Value value(String stringValue)
}

class Value {
  Object object
  String valueAsString
  String valueAsInnerString
}

Table "1" *-- "*" Type : specified by

Row "1" o-- "*" Value : contains

Value "*" *-- "1" Type : has

Type <|-- Int
Type <|-- Char
Type <|-- Real
Type <|-- IntInterval
Type <|-- TextFile
Type <|-- Longint
Type <|-- HtmlFile
