client -> (show tables list)
client -> (show table signature)
client -> (create table)
client -> (remove table)
client -> (drop database)
client -> (select data from table)
client -> (insert row into table)
client -> (remove row from table)
client -> (find difference between two tables)
client -> (remove duplicates from table)
